# Generated by Django 5.0.6 on 2024-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('s_id', models.CharField(max_length=9)),
                ('room', models.CharField(choices=[('1', '104'), ('2', '201'), ('3', '202'), ('4', '209'), ('5', '210'), ('6', '309'), ('7', '310'), ('8', '404')], default='NULL', max_length=3)),
                ('time_in', models.CharField(choices=[('1', '7:00'), ('2', '9:00'), ('3', '11:00'), ('4', '13:00'), ('5', '15:00'), ('6', '17:00')], default='NULL', max_length=5)),
                ('time_out', models.CharField(choices=[('1', '7:00'), ('2', '9:00'), ('3', '11:00'), ('4', '13:00'), ('5', '15:00'), ('6', '17:00')], default='NULL', max_length=5)),
            ],
        ),
    ]
