# Generated by Django 5.0.6 on 2024-07-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbook',
            name='room',
            field=models.CharField(choices=[('104', 'Room 104'), ('201', 'Room 201'), ('202', 'Room 202'), ('209', 'Room 209'), ('210', 'Room 210'), ('309', 'Room 309'), ('310', 'Room 310'), ('404', 'Room 404')], max_length=3),
        ),
        migrations.AlterField(
            model_name='formbook',
            name='time_in',
            field=models.CharField(choices=[('07:00', '7:00 AM'), ('09:00', '9:00 AM'), ('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='formbook',
            name='time_out',
            field=models.CharField(choices=[('07:00', '7:00 AM'), ('09:00', '9:00 AM'), ('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=5),
        ),
    ]
